#!/usr/bin/env bash

if
  [[ -s "/usr/local/rvm/gems/ruby-2.1.0@global/environment" ]]
then
  source "/usr/local/rvm/gems/ruby-2.1.0@global/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/gems/ruby-2.1.0@global/environment'" >&2
  exit 1
fi
